"""add photo_path and system_settings

Revision ID: 292c07a6e1d2
Revises: 0003_dnd_preferences
Create Date: 2026-06-03 14:05:43.746530
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '292c07a6e1d2'
down_revision: Union[str, Sequence[str], None] = '0003_dnd_preferences'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='housekeeping'
    )
    op.add_column('cleaning_queue_entries', sa.Column('photo_path', sa.String(length=512), nullable=True), schema='housekeeping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleaning_queue_entries', 'photo_path', schema='housekeeping')
    op.drop_table('system_settings', schema='housekeeping')
    # ### end Alembic commands ###
