"""add auth_user_id and cleaning_requests

Revision ID: b04f9c7f5203
Revises: 0007_reservations
Create Date: 2026-06-03 14:12:28.712455
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b04f9c7f5203'
down_revision: Union[str, Sequence[str], None] = '0007_reservations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
