"""add must_change_password and audit_logs

Revision ID: 85b7f50501df
Revises: 99d5566f6afc
Create Date: 2026-06-03 17:00:41.310477
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '85b7f50501df'
down_revision: Union[str, Sequence[str], None] = '99d5566f6afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_audit_logs_action'), 'audit_logs', ['action'], unique=False, schema='auth')
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password', schema='auth')
    op.drop_index(op.f('ix_auth_audit_logs_action'), table_name='audit_logs', schema='auth')
    op.drop_table('audit_logs', schema='auth')
    # ### end Alembic commands ###
