"""add guest fields to users

Revision ID: 99d5566f6afc
Revises: 0001_initial
Create Date: 2026-06-03 14:04:59.042562
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '99d5566f6afc'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('guest_id', sa.UUID(), nullable=True), schema='auth')
    op.add_column('users', sa.Column('room_id', sa.UUID(), nullable=True), schema='auth')
    op.add_column('users', sa.Column('room_number', sa.Integer(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'room_number', schema='auth')
    op.drop_column('users', 'room_id', schema='auth')
    op.drop_column('users', 'guest_id', schema='auth')
    # ### end Alembic commands ###
